easy_admin:
  design:
    brand_color: "#222"
    menu:
      - label: "ENAISS"
        icon: "medkit"
        children:
          - {entity: DirecteurHopital, icon: "street-view", label: "Directeur Hopital"}
          - {entity: SageFemme, icon: "female", label: "Sage femme"}
          - {entity: Hopital, icon: "hospital-o", label: "Hopital"}
          - {entity: DeclarationNaiss, icon: "folder-o", label: "Declaration Naissance"}
      - label: "Prefecture"
        icon: "medkit"
          - {entity: DirecteurPrefecture, icon: "street-view", label: "Directeur Prefecture"}
          - {entity: AgentPrefecture, icon: "user", label: "Agent Prefecture"}
          - {entity: Prefecture, icon: "building-o", label: "Prefecture"}
          - {entity: Extrait, icon: "file-text-o", label: "Extrait"}
      - label: "Economie"
        icon: "medkit"
          - {entity: AgentEconomie, icon: "bar-chart", label: "Agent Economie"}