easy_admin:
  entities:
    DeclarationNaiss:
      class: App\Entity\DeclarationNaiss
      role: [ROLE_SUPER_ADMIN]
      list:
        title: "liste des Declaration Naissance"
        help: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore,
        "
        actions:
          - {name: "new", label: "creer une Declaration", icon: "plus fa-fw" }
          - {name: "edit", icon: "pencil", label: false, css_class: "btn btn-outline-secondary"}
          - {name: "delete", label: false, icon: "trash", css_class: "btn btn-outline-danger"}

        fields:
          - {property : id, label: '#ID'}
          - {property : sousigne, label: 'Sousigne'}
          - {property : epouse, label: 'Epouse'}
          - {property : date_heure_accouch, label: 'date accouchement'}
          - {property : prenom_enfant, label: 'Pere'}
          - {property : date_decla, label: 'date_declaration'}
      new:
        title: "Formulaire pour creer une Declaration"
        help: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        ."

      form:
        form_options: { validation_groups: ['default']}
        fields:
          - {property : sousigne, label: 'sousigne'}
          - {property : nomme, label: 'nomme'}
          - {property : epouse, label: 'epouse'}
          - {property : age_mere, label: 'age_mere'}
          - {property : profession, label: 'profession'}
          - {property : adress, label: 'adress'}
          - {property : date_naiss, label: 'date_naiss'}
          - {property : date_heure_accouch, label: 'date_accouch'}
          - {property : sexe_enfant, label: 'sexe_enfant'}
          - {property : nom_enfant, label: 'nom enfant'}
          - {property : prenom_enfant, label: 'prenom enfant'}
          - {property : date_decla, label: 'date_decla'}
          - {property : lieu_declare, label: 'lieu_declare'}