easy_admin:
  entities:
    DirecteurHopital:
      class: App\Entity\DirecteurHopital
      list:
        title: "liste des Directeurs des Hopitaux"
        help: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore,
        "
        actions:
          - {name: "new", label: "creer un Directeur Hopital", icon: "plus fa-fw" }
          - {name: "edit", icon: "pencil", label: false, css_class: "btn btn-outline-secondary"}
          - {name: "delete", label: false, icon: "trash", css_class: "btn btn-outline-danger"}

        fields:
          - {property : id, label: '#ID'}
          - {property : nom, label: 'Nom&Prenom'}
          - {property : telephone, label: 'Telephone'}
          - {property : email, label: 'Email'}

      new:
        title: "Formulaire pour creer Directeurs"
        help: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        ."

      form:
        form_options: { validation_groups: ['default']}
        fields:
          - {property : nom, label: 'Nom'}
          - {property : prenom, label: 'Prenom'}
          - {property : telephone, label: 'Telephone'}
          - {property : email, label: 'Email'}
