easy_admin:
  entities:
    Extrait:
      class: App\Entity\Extrait
      list:
        title: "liste des Extraits"
        help: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore,
        "
        actions:
          - {name: "new", label: "creer une Extrait", icon: "plus fa-fw" }
          - {name: "edit", icon: "pencil", label: false, css_class: "btn btn-outline-secondary"}
          - {name: "delete", label: false, icon: "trash", css_class: "btn btn-outline-danger"}

        fields:
          - {property : id, label: '#ID'}
          - {property : date_naiss, label: 'Date_naiss'}
          - {property : nom_enfant, label: 'Nom_enfant'}
          - {property : sexe_enfant, label: 'Sexe_enfant'}
          - {property : nom_pere, label: 'Nom_pere'}
          - {property : nom_mere, label: 'Nom_mere'}

      new:
        title: "Formulaire pour creer un Extrait"
        help: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        ."

      form:
        form_options: { validation_groups: ['default']}
        fields:
          - {property : date_naiss, label: 'date_naiss'}
          - {property : lieu_naiss, label: 'lieu_naiss'}
          - {property : heure_naiss, label: 'heure_naiss'}
          - {property : minute_naiss, label: 'minute_naiss'}
          - {property : nom_enfant, label: 'nom_enfant'}
          - {property : sexe_enfant, label: 'sexe_enfant'}
          - {property : nom_pere, label: 'nom_pere'}
          - {property : date_naiss_pere, label: 'date_naiss_pere'}
          - {property : adress_naiss_pere, label: 'adress_naiss_pere'}
          - {property : profession_pere, label: 'profession_pere'}
          - {property : ville_pere, label: 'ville_pere'}
          - {property : nom_mere, label: 'nom_mere'}
          - {property : date_naiss_mere, label: 'date_naiss_mere'}
          - {property : adress_naiss_mere, label: 'adress_naiss_mere'}
          - {property : profession_mere, label: 'profession_mere'}
          - {property : ville_mere, label: 'ville_mere'}
          - {property : mention_marginal, label: 'mention_marginal'}
          - {property : prefecture, label: 'prefecture'}

          
