easy_admin:
  entities:
    Prefecture:
      class: App\Entity\Prefecture
      list:
        title: "liste des Prefecture"
        help: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore,
        "
        actions:
          - {name: "new", label: "creer un Prefecture", icon: "plus fa-fw" }
          - {name: "edit", icon: "pencil", label: false, css_class: "btn btn-outline-secondary"}
          - {name: "delete", label: false, icon: "trash", css_class: "btn btn-outline-danger"}

        fields:
          - {property : id, label: '#ID'}
          - {property : adress, label: 'Adress'}
          - {property : telephone, label: 'Telephone'}
          - {property : email, label: 'Email'}

      new:
        title: "Formulaire pour creer une Prefecture"
        help: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        ."

      form:
        form_options: { validation_groups: ['default']}
        fields:
          - {property : adress, label: 'Adress'}
          - {property : email, label: 'Email'}
          - {property : telephone, label: 'Telephone'}